
##### Do not write any parameters which not use #####
# split_data
test_size: 0.2
random_state: 1111

# LightGBM_model
folds: 5
n_estimators: 5000
boosting_type: 'gbdt'
objective: 'regression'
metric: 'rmse'
num_leaves: 50
#subsample: 0.85
#subsample_freq: 1
learning_rate: 0.01
#feature_fraction: 0.9
max_depth: 5
#lambda_l1: 0.1
#lambda_l2: 0.1
verbose: -1
early_stopping_rounds: 1000
#eval_metric: 'auc'
seed: 114514