
##### Do not write any parameters which not use #####
# split_data
test_size: 0.2
random_state: 1111
seed: 114514

# LightGBM_model
folds: 5
n_estimators: 5000
boosting_type: 'gbdt'
lgb_objective: 'regression'
metric: 'rmse'
num_leaves: 50
#subsample: 0.85
#subsample_freq: 1
learning_rate: 0.01
#feature_fraction: 0.9
max_depth: 5
#lambda_l1: 0.1
#lambda_l2: 0.1
verbose: -1
early_stopping_rounds: 1000
#eval_metric: 'auc'


# XGBoost_model
target: 'y'
num_rounds: 1000
xgb_objective: 'regression'
eval_metric: 'auc'
booster: 'gbtree'
n_jobs: 4
tree_method: 'hist'
eta: 0.01
grow_policy: 'lossguide'
max_delta_step: 2
#seed: 538
colsample_bylevel: 0.9
colsample_bytree: 0.8
gamma: 1.0
learning_rate: 0.001
max_bin: 64
max_depth: 6
max_leaves: 10
min_child_weight: 10
reg_alpha: 1e-06
reg_lambda: 1.0
subsample: 0.7